name: Deploy to AWS

on:
  workflow_call:
    inputs:
      environment-name:
        required: true
        type: string
      container-image:
        required: true
        type: string
        default: ${{ github.event.repository.name }}:${{ github.sha }}
      worker-container-image:
        required: true
        type: string
        default: ${{ github.event.repository.name }}:${{ github.sha }}

env:
  AWS_REGION: us-west-2

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.STRONGMIND_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.STRONGMIND_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Deploy with Pulumi
      env:
        PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        CONTAINER_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.container-image }}
        WORKER_CONTAINER_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.worker-container-image }}
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        ENVIRONMENT_NAME: ${{ inputs.environment-name }}
      run: |
        cd ./infrastructure/
        pulumi login s3://pulumi-state-sm/${{ github.event.repository.name }}
        pulumi stack init ${{ inputs.environment-name }} --non-interactive || true
        pulumi stack select ${{ inputs.environment-name }}
        pulumi up --yes