name: Deploy to AWS

on:
  workflow_call:
    inputs:
      environment-name:
        required: true
        type: string
      commit-sha:
        required: false
        type: string
      web-repository-name:
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      worker-repository-name:
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      pulumi-command:
        required: false
        type: string
        default: 'up'
      pulumi-refresh:
        required: false
        type: string
        default: 'true'

jobs:
  deploy-auto:
    name: Autodeploy to ECS
    uses: strongmind/public-reusable-workflows/.github/workflows/aws-deploy-with-pulumi.yml@Bel-4071
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    with:
      environment-name: ${{ inputs.environment-name }}
      web-container-image: ${{ inputs.web-repository-name }}:${{ github.event.workflow_run.head_sha }}
      worker-container-image: ${{ inputs.worker-repository-name }}:${{ github.event.workflow_run.head_sha }}
      pulumi-command: ${{ inputs.pulumi-command }}
      pulumi-refresh: ${{ inputs.pulumi-refresh }}
    secrets: inherit

  deploy-manual:
    name: Manually deploy to ECS
    uses: strongmind/public-reusable-workflows/.github/workflows/aws-deploy-with-pulumi.yml@Bel-4071
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.commit-sha == '' }}
    with:
      environment-name: ${{ inputs.environment-name }}
      web-container-image: ${{ inputs.web-repository-name }}:${{ github.sha }}
      worker-container-image: ${{ inputs.worker-repository-name }}:${{ github.sha }}
      pulumi-command: ${{ inputs.pulumi-command }}
      pulumi-refresh: ${{ inputs.pulumi-refresh }}
    secrets: inherit


  deploy-manual-with-sha:
    name: Manually deploy to ECS with SHA
    uses: strongmind/public-reusable-workflows/.github/workflows/aws-deploy-with-pulumi.yml@Bel-4071
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.commit-sha != '' }}
    with:
      environment-name: ${{ inputs.environment-name }}
      web-container-image: ${{ inputs.web-repository-name }}:${{ inputs.commit-sha }}
      worker-container-image: ${{ inputs.worker-repository-name }}:${{ inputs.commit-sha }}
      pulumi-command: ${{ inputs.pulumi-command }}
      pulumi-refresh: ${{ inputs.pulumi-refresh }}
    secrets: inherit
