name: Build Python Package for Deployment Components

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'deployment/**'

jobs:
  build:
    name: Build and Publish
    uses: strongmind/public-reusable-workflows/.github/workflows/python-package-build.yml@main
    secrets: inherit