name: 'Build and publish docker container'

on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker
      run: docker build -t app . -f ${{ inputs.dockerfile_path }}