name: Notify release to slack

on:
  workflow_call:

jobs:
  send-slack:
    name: Send slack message
    runs-on: ubuntu-latest
    steps:
    - name: Get Commit Message
      id: get-commit-message
      run: |
        MSG=$(git log --format=%B -n 1 ${{ github.sha }})
        echo "message=${MSG}" >> "$GITHUB_OUTPUT"
    - name: Send message to slack
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "repository_url": "${{ github.server_url }}/${{ github.repository }}",
            "repository_name": "${{ github.event.repository.name }}",
            "repository_owner": "${{ github.event.repository.owner.login }}",
            "commit_sha": "${{ github.sha }}",
            "commit_url": "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}",
            "commit_message": "${{ steps.get-commit-message.outputs.message }}",
            "actor": "${{ github.actor }}",
            "actor_url": "${{ github.server_url }}/${{ github.actor }}",
            "actor_avatar": "${{ github.event.sender.avatar_url }}",
            "workflow_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "workflow_name": "${{ github.workflow }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_RELEASE_NOTIFICATIONS_URL }}
