name: Notify release to slack

on:
  workflow_call:

jobs:
  send-slack:
    name: Send slack message
    runs-on: ubuntu-latest
    steps:
    - name: Send message to slack
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "message": "${{ github.event.repository.name }} deployment: ${{ job.status }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_RELEASE_NOTIFICATIONS_URL }}
