name: Manual Deploy or Preview Azure to AWS

on:
  workflow_call:
    inputs:
      pulumi_action:
        description: 'Pulumi action to perform'
        required: true
        type: string
      workdir:
        description: 'Working directory'
        required: true
        type: string
      stack:
        description: 'Stack to use'
        required: true
        type: string
      aws_region:
        description: 'aws region'
        required: true
        type: string

jobs:
  manual_stage:
    if: ${{ contains(github.event.inputs.stack, 'stage') }}
    uses: strongmind/public-reusable-workflows/.github/workflows/pulumi.yml@caylent_main
    with:
      pulumi_command: ${{ github.event.inputs.pulumi_action }}
      pulumi_stack: ${{ github.event.inputs.stack }}
      aws_region: ${{ github.event.inputs.aws_region }}
      working_directory: ${{ github.event.inputs.workdir }}
      role_to_assume: ${{ vars.ROLE_NAME_TO_ASSUME_STRONGMIND_STAGE }}
      state_bucket: ${{ vars.STATE_BUCKET_STAGE }}
    secrets:
      pulumi_config_passphrase: ${{ secrets.PULUMI_CONFIG_PASSPHRASE_STAGE }}

  manual_prod:
    if: ${{ contains(github.event.inputs.stack, 'prod') || contains(github.event.inputs.stack, 'main') }}
    uses: strongmind/public-reusable-workflows/.github/workflows/pulumi.yml@caylent_main
    with:
      pulumi_command: ${{ github.event.inputs.pulumi_action }}
      pulumi_stack: ${{ github.event.inputs.stack }}
      aws_region: ${{ github.event.inputs.aws_region }}
      working_directory: ${{ github.event.inputs.workdir }}
      role_to_assume: ${{ vars.ROLE_NAME_TO_ASSUME_STRONGMIND_PROD }}
      state_bucket: ${{ vars.STATE_BUCKET_PROD }}
    secrets:
      pulumi_config_passphrase: ${{ secrets.PULUMI_CONFIG_PASSPHRASE_PROD }}