name: Build Python Package

on: 
  workflow_call:

jobs:
  Build-Publish:
    name: Build and Publish
    runs-on: macos-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4 
      with:
        python-version: "3.10"

    # hardcoded pip version to avoid bug in pip 23.2 (please reference to https://strongmind.atlassian.net/browse/DEVOPS-9181?focusedCommentId=234025)
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        make install

    - name: Pytest
      run: |
        make test

    - name: package files
      run: |
        make build

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{secrets.PYPITOKEN}}
