name: Build Python Package

on: 
  workflow_call:

jobs:
  Build-Publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4 
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip==23.1.2
        make install

    - name: Pytest
      run: |
        make test

    - name: package files
      run: |
        make build

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{secrets.PYPITOKEN}}
