name: Deploy Rails

on:
  workflow_call:
    inputs:
      environment-name:
        required: true
        type: string
      container-image:
        required: true
        type: string


env:
  AWS_REGION: us-west-2

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.STRONGMIND_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.STRONGMIND_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy with Pulumi
      env:
        PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        CONTAINER_IMAGE: ${{ inputs.container-image }}
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        ENVIRONMENT_NAME: ${{ inputs.environment-name }}
      run: |
        cd ./infrastructure/
        pulumi login s3://pulumi-state-sm/${{ github.event.repository.name }}
        pulumi stack init ${{ github.event.repository.name }}-${{ inputs.environment-name }} --non-interactive || true
        pulumi stack select ${{ github.event.repository.name }}-${{ inputs.environment-name }}
        pulumi up --yes