name: Deploy Rails

on:
  workflow_call:
    inputs:
      environment-name:
        required: true
        type: string


env:
  AWS_REGION: us-west-2

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.STRONGMIND_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.STRONGMIND_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy with Pulumi
      env:
        PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      run: |
        cd ./infrastructure/
        pulumi login s3://pulumi-state-sm/${{ github.event.repository.name }}
        pulumi stack init ${{ github.event.repository.name }}-${{ github.jobs.deploy.environment }} --non-interactive || true
        pulumi stack select ${{ github.event.repository.name }}-${{ github.jobs.deploy.environment }}
        pulumi up --yes