name: "rspec test"

on:
  workflow_call:
    inputs:
      ruby-version:
        description: "Ruby version"
        required: false
        default: "3.2.2"
        type: string
      bundle-no-assets:
        description: "Bundle assets"
        required: false
        default: bundle exec rails db:prepare db:migrate assets:precompile
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Start Postgres
        run: sudo systemctl start postgresql.service
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby-version }}

      - run: |
          bundle config gems.contribsys.com ${{ secrets.BUNDLE_GEMS__CONTRIBSYS__COM }}
          bundle install
          ${{ inputs.bundle-no-assets }}
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          RAILS_ENV: test

      - name: Check for Secret availability
        id: secret-check
        # perform secret check & put boolean result as an output
        shell: bash
        run: |
          if [ "${{ secrets.CC_TEST_REPORTER_ID }}" != '' ]; then
            echo "available=true" >> $GITHUB_OUTPUT;
          else
            echo "available=false" >> $GITHUB_OUTPUT;
          fi
          
      - name: Test
        if: ${{ steps.secret-check.outputs.available != 'true' }}
        run: |
          bundle exec rspec

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        id: codeclimate
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        with:
          coverageCommand: 'bundle exec rspec'
          debug: true



      - name: Capture output from codeclimate-action
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        run: |
          bundle exec rspec
          echo "==========================+++++++++++++++++++++++++++++=========================="
          echo "Code Climate Action output: ${{ steps.codeclimate.outputs.output }}" 
          echo "==========================+++++++++++++++++++++++++++++=========================="
          echo "Code Climate Action output: ${{ steps.codeclimate.outputs.output }}" 
          

      - name: Archive coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-${{ github.sha }}
          path: ${{ github.workspace }}/rspec-output